changed secret validation logic and commented out the old logic
Signed-off-by: Matan Avital <matavital13@gmail.com>

diff --git a/.github/workflows/kubescape-cli-e2e-tests.yaml b/.github/workflows/kubescape-cli-e2e-tests.yaml
--- a/.github/workflows/kubescape-cli-e2e-tests.yaml
+++ b/.github/workflows/kubescape-cli-e2e-tests.yaml
@@ -43,7 +43,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       TEST_NAMES: ${{ steps.export_tests_to_env.outputs.TEST_NAMES }}
-      is-secret-set: ${{ steps.check-secret-set.outputs.is-secret-set }}
+      # is-secret-set: ${{ steps.check-secret-set.outputs.is-secret-set }}
     steps:
       - name: check if the necessary secrets are set in github secrets
         id: check-secret-set
@@ -55,7 +55,23 @@ jobs:
           SECRET_KEY: ${{ secrets.SECRET_KEY_PROD }}
           REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
           REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
-        run: "echo \"is-secret-set=${{ env.CUSTOMER != '' && \n                        env.USERNAME != '' &&\n                        env.PASSWORD != '' &&\n                        env.CLIENT_ID != '' &&\n                        env.SECRET_KEY != '' &&\n                        env.REGISTRY_USERNAME != '' &&\n                        env.REGISTRY_PASSWORD != ''\n                      }}\" >> $GITHUB_OUTPUT\n"
+
+        # run: "echo \"is-secret-set=${{ env.CUSTOMER != '' && \n                        env.USERNAME != '' &&\n                        env.PASSWORD != '' &&\n                        env.CLIENT_ID != '' &&\n                        env.SECRET_KEY != '' &&\n                        env.REGISTRY_USERNAME != '' &&\n                        env.REGISTRY_PASSWORD != ''\n                      }}\" >> $GITHUB_OUTPUT\n"
+        # "is-secret-set" validatin (and var) is commented because we add the secret validator function down here.
+        # We commented it out because we revised the secret validation process. We want the pipeline to fail if even one of the secrets is not set.
+        
+        run: |
+              env_vars=("CUSTOMER" "USERNAME" "PASSWORD" "CLIENT_ID" "SECRET_KEY" "REGISTRY_USERNAME" "REGISTRY_PASSWORD")
+              
+              for var_name in "${env_vars[@]}"; do
+                var_value="${!var_name}"
+                if [[ -z "${var_value// /}" ]]; then
+                  echo "Environment variable '$var_name' is empty, null, or contains only whitespace. Failing the workflow."
+                  exit 1
+                fi
+              done
+              
+              echo "All environment variables are valid. Proceeding with the workflow."
 
       - id: export_tests_to_env
         name: set test name
@@ -71,7 +87,9 @@ jobs:
       matrix:
         TEST: ${{ fromJson(needs.wf-preparation.outputs.TEST_NAMES) }}
     needs: [wf-preparation]
-    if: ${{ (needs.wf-preparation.outputs.is-secret-set == 'true') && (always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled'))) }}
+    # Down here we have the previous if statement that contains the "is-secret-set" validation.
+    # if: ${{ (needs.wf-preparation.outputs.is-secret-set == 'true') && (always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled'))) }}
+    if: ${{ (always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled'))) }}
     runs-on: ubuntu-latest # This cannot change
     steps:
 
