added a secret validation mechanism
Signed-off-by: Matan Avital <matavital13@gmail.com>

diff --git a/.github/workflows/kubescape-cli-e2e-tests.yaml b/.github/workflows/kubescape-cli-e2e-tests.yaml
--- a/.github/workflows/kubescape-cli-e2e-tests.yaml
+++ b/.github/workflows/kubescape-cli-e2e-tests.yaml
@@ -55,9 +55,18 @@ jobs:
           SECRET_KEY: ${{ secrets.SECRET_KEY_PROD }}
           REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
           REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
-        if: ${{ env.CUSTOMER == '' }}
-        run: 'echo "echo the secret \"MY_SECRET\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"'
-        # run: "echo \"is-secret-set=${{ env.CUSTOMER != '' && \n                        env.USERNAME != '' &&\n                        env.PASSWORD != '' &&\n                        env.CLIENT_ID != '' &&\n                        env.SECRET_KEY != '' &&\n                        env.REGISTRY_USERNAME != '' &&\n                        env.REGISTRY_PASSWORD != ''\n                      }}\" >> $GITHUB_OUTPUT\n"
+        run: |
+              env_vars=("CUSTOMER" "USERNAME" "PASSWORD" "CLIENT_ID" "SECRET_KEY" "REGISTRY_USERNAME" "REGISTRY_PASSWORD")
+              
+              for var_name in "${env_vars[@]}"; do
+                var_value="${!var_name}"
+                if [[ -z "${var_value// /}" ]]; then
+                  echo "Environment variable '$var_name' is empty, null, or contains only whitespace. Failing the workflow."
+                  exit 1
+                fi
+              done
+              
+              echo "All environment variables are valid. Proceeding with the workflow."
 
       - id: export_tests_to_env
         name: set test name
