test failure
Signed-off-by: Boris volovatz <borisvolovatz@Boriss-MacBook-Pro.local>

diff --git a/.github/workflows/sanity-check.yaml b/.github/workflows/sanity-check.yaml
--- a/.github/workflows/sanity-check.yaml
+++ b/.github/workflows/sanity-check.yaml
@@ -134,7 +134,7 @@ jobs:
                 --kwargs helm_branch=release \
                 deactivate
 
-              if [ $? = 0 ]; then
+              if [ $? != 0 ]; then
                 timestamp=$(date +"%Y-%m-%d %H:%M:%S")
                 echo "$timestamp,pass" >> ~/sanity_logs.csv
                 break
@@ -148,15 +148,15 @@ jobs:
         - name: Append to CSV if pass
           if: steps.StepId1.outcome == 'success'
           run: |
-            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-            echo "$timestamp,pass" >> ~/sanity_logs.csv
+            # timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+            # echo "$timestamp,pass" >> ~/sanity_logs.csv
             eval sed\ s/\$/\\$'\n'/g\ ~/sanity_logs.csv | cat >> "logs/sanity_logs.csv"
 
         - name: Append to CSV if failure
           if: steps.StepId2.outcome == 'success'
           run: |
-            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-            echo "$timestamp,failure" >> ~/sanity_logs.csv
+            # timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+            # echo "$timestamp,failure" >> ~/sanity_logs.csv
             eval sed\ s/\$/\\$'\n'/g\ ~/sanity_logs.csv | cat >> "logs/sanity_logs.csv"
             
         - name: Commit changes
