test for retry
Signed-off-by: Boris volovatz <borisvolovatz@Boriss-MacBook-Pro.local>

diff --git a/.github/workflows/sanity-check.yaml b/.github/workflows/sanity-check.yaml
--- a/.github/workflows/sanity-check.yaml
+++ b/.github/workflows/sanity-check.yaml
@@ -106,13 +106,26 @@ jobs:
             echo " ${{ matrix.TEST }} " >/tmp/testhistory
             cat /tmp/testhistory
             source systests_python_env/bin/activate
-            python3 systest-cli.py             \
-              -t ${{ matrix.TEST }}            \
-              -b production                    \
-              -c CyberArmorTests               \
-              --logger DEBUG                   \
-              --kwargs helm_branch=release     \
-            deactivate
+            max_attempts=2
+            attempt=1
+            while [ $attempt -le $max_attempts ]
+            do
+              python3 systest-cli.py \
+              -t ${{ matrix.TEST }} \
+              -b production \
+              -c CyberArmorTests \
+              --logger DEBUG \
+              --kwargs helm_branch=release \
+              deactivate
+              if [ $? -eq 0 ]; then
+                echo "Test passed"
+                break
+              else
+                echo "Test failed, increment attempt count"
+                attempt=$((attempt + 1))
+                sleep 10
+              fi
+            done
 
         - name: run-tests-repeated
           if: ${{ inputs.IF_FAILED == true }}
